CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rut TEXT UNIQUE,
  name TEXT,
  email TEXT,
  embedding BLOB,
  img BLOB,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event TEXT,
  details TEXT,
  ts TEXT DEFAULT CURRENT_TIMESTAMP
);
