version: "3.9"

services:
  db:
    image: postgres:14
    container_name: face_db
    restart: always
    environment:
      POSTGRES_DB: faces
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  central:
    build: ./central
    container_name: face_central
    env_file:
      - ./central/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./central:/app

  local:
    build: ./local
    container_name: face_local
    env_file:
      - ./local/.env
    depends_on:
      - central
    ports:
      - "8500:8500"
    volumes:
      - ./local:/app

volumes:
  postgres_data:
